name: Deploy Laravel Application to Production


on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: 8.4
            
            - name: install Composer Dependencies
              run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist 


            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '22.21.1'
            
            - name: Install NPM dependencies
              run: npm run build

            - name: Synchronize files to server
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                server: ${{ secrets.FTP_SERVER }}
                username: ${{ secrets.FTP_USERNAME }}
                password: ${{ secrets.FTP_PASSWORD }}
                port: 21
                # Upload everything built in the workspace runner
                local-dir: ./
                # Path inside InfinityFree (usually htdocs or yourdomain.com/htdocs)
                server-dir: ./htdocs/
                # Keep files safe on the server
                exclude: |
                    **/.git*
                    **/.git*/**
                    **/node_modules/**
                    .env
                
         
            


